
package ventanas;

import java.io.*;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class interfaz extends javax.swing.JFrame {

    public static String buscarUser(String cadCompleta) {
        String[] arrDatos = cadCompleta.split(",");
        return arrDatos[0].trim();
    }

    public static String buscarPass(String cadCompleta) {
        int poscoma = cadCompleta.lastIndexOf(",");
        String resultado = cadCompleta.substring(poscoma + 1);
        return resultado.trim();
    }

    //Encriptacion
    public static String getHash(String txt, String hashType) {

        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance(hashType);
            byte[] array = md.digest(txt.getBytes());
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            System.out.println(e.getMessage());
        }
        return null;
    }

    public static String sha1(String txt) {
        return getHash(txt, "SHA1");
    }

    public interfaz() {
        initComponents();
        //icono de imagen
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/escudoUDG1.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/Imagenes/escudoUDG1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        ccontrasena = new javax.swing.JPasswordField();
        usuario = new javax.swing.JTextField();
        sesion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(204, 204, 204));
        logo.setForeground(new java.awt.Color(204, 204, 204));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/udg.jpg"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 550, 280));

        user.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        user.setText("USUARIO:");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setText("PASSWORD:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        ccontrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ccontrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccontrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(ccontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 180, 30));

        usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 180, 30));

        sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sesion.setText("INGRESAR");
        sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sesionMouseClicked(evt);
            }
        });
        sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sesionActionPerformed(evt);
            }
        });
        getContentPane().add(sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        salir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_blanco.jpg"))); // NOI18N
        fondo.setOpaque(true);
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, 680, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ccontrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccontrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccontrasenaActionPerformed

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sesionMouseClicked

        try {
            //Obtener usuarios y contrasenas
            BufferedReader entrada = new BufferedReader(new FileReader("Usuarios.txt"));
            String linea = "";
            boolean acces = false;
            while ((linea = entrada.readLine()) != null && acces == false) {
                String user = buscarUser(linea);
                String password = buscarPass(linea);
                

                String pass = new String(ccontrasena.getPassword());
                // encripta lo que escribes en el pasword
                String passSha1 = sha1(pass);
                // validar que sea correcto el ususario y contrasena

                if (usuario.getText().equalsIgnoreCase(user) && passSha1.equalsIgnoreCase(password)) {
                    Interfaz2 in = new Interfaz2();
                    in.setVisible(true);
                    acces = true;
                    dispose();
                }

            }

            if (acces == false) {
                JOptionPane.showMessageDialog(this, "Usuario o Password incorrecto");
            }
        } catch (IOException e) {
        }


    }//GEN-LAST:event_sesionMouseClicked

    private void sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // acceso visible 
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ccontrasena;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel password;
    private javax.swing.JButton salir;
    private javax.swing.JButton sesion;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
