package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.RandomAccessFile;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*Autor: Christopher Tamayo Cazarez
  Numero:  7
  Titulo de practica: Kiosko
 */
public class Interfaz2 extends javax.swing.JFrame {

    Scanner leer = new Scanner(System.in);
    final static int CONS = 2179;
    private static Registro aCrn[] = new Registro[CONS];
    private static Registro aClave[] = new Registro[CONS];
    private static Registro aMateria[] = new Registro[CONS];
    private static Registro aNombre[] = new Registro[CONS];
    private static Registro aApellido[] = new Registro[CONS];

    DefaultTableModel dtm;

    /**
     * Creates new form Interfaz2
     */
    public Interfaz2() {
        initComponents();
        // Titulos de tabla
        String datos[][] = {};
        String[] titulos = new String[]{"                                                                                 REGISTROS ECONTRADOS "};
        dtm = new DefaultTableModel(datos, titulos);
        tblDatos.setModel(dtm);
        // icono
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/escudoUDG1.png")).getImage());
        //Localizacion de ventana
        this.setLocationRelativeTo(null);
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("/Imagenes/escudoUDG1.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSplitPane1 = new javax.swing.JSplitPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextbuscar = new javax.swing.JTextField();
        jComboBoxOpciones = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButtonBuscar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jRadioButton1.setText("jRadioButton1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(0, 51, 204));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 70, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siiau.JPG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 650, 70));

        jTextbuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 30));

        jComboBoxOpciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CRN", "CLAVE", "MATERIA", "NOMBRE", "APELLIDO" }));
        jComboBoxOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 180, 30));

        tblDatos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDatos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 680, 320));

        jButtonBuscar.setBackground(new java.awt.Color(0, 0, 102));
        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 80, 30));

        jButtonEliminar.setBackground(new java.awt.Color(0, 51, 204));
        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 90, 30));

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar nuevo usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, 30));

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_blanco.jpg"))); // NOI18N
        getContentPane().add(jLabelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 720, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jComboBoxOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOpcionesActionPerformed
        // Pestana de opciones


    }//GEN-LAST:event_jComboBoxOpcionesActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // uso de opciones en combobox

        try {
            int i = jComboBoxOpciones.getSelectedIndex();
            // buscar por crn
//            if (i.equals("CRN")); // buscar por clave
//            else if (i.equals("CLAVE")); // buscra por nombre
//            else if (i.equals("NOMBRE")); // buscar por appellido
//            else if (i.equals("APELLIDO")); // buscar por materia
//            else if (i.equals("MATERIA"));

            String buscar = jTextbuscar.getText();
            String elem = "";
            int pos = 0;
            long puntero = 0;
            boolean band = false;
            String reg = "";
            int cont = 0;
            long dire = 0;
            String cadRegistro = "";

            RandomAccessFile archivoDatos = new RandomAccessFile("siiau2.dat", "r");
            RandomAccessFile indice1 = new RandomAccessFile("crnindice.ind", "rw");
            RandomAccessFile indice2 = new RandomAccessFile("claveindice.ind", "rw");
            RandomAccessFile indice3 = new RandomAccessFile("materiaindice.ind", "rw");
            RandomAccessFile indice4 = new RandomAccessFile("nombreindice.ind", "rw");
            RandomAccessFile indice5 = new RandomAccessFile("apellidoindice.ind", "rw");
            if (i == 0) {
                indice1.seek(0);

                while (elem.compareTo(buscar) < 0 && puntero != indice1.length() && band == false) {

                    dire = indice1.readLong();

                    elem = "";
                    cadRegistro = "";
                    char letra = (char) indice1.readByte();
                    while (letra != '|') {
                        elem = elem + letra;
                        letra = (char) indice1.readByte();
                    }

                    cont++;
                    if (elem.compareTo(buscar) == 0) {

                        archivoDatos.seek(dire);

                        String longitud = "";
                        char letra2 = (char) archivoDatos.readByte();

                        while (letra2 != '|') {

                            longitud = longitud + letra2;
                            letra2 = (char) archivoDatos.readByte();
                        }

                        int largo = Integer.parseInt(longitud);

                        reg = "";
                        for (int j = 0; j < largo; j++) {
                            reg = reg + (char) archivoDatos.readByte();

                        }
                        reg = reg.replaceAll("~", "Ñ");
                        band = true;
                        dtm.addRow(new Object[]{reg});
                        elem = "";
                    }
                    puntero = indice1.getFilePointer();
                }
                if (band == false) {
                    JOptionPane.showMessageDialog(this, "No se encontro el crn");
                }

                //--------------------------------------------------------------------------
            } else if (i == 1) {
                indice2.seek(0);
                while (elem.compareTo(buscar) < 0 && puntero != indice2.length()) {

                    dire = indice2.readLong();

                    elem = "";
                    cadRegistro = "";
                    char letra = (char) indice2.readByte();
                    while (letra != '|') {
                        elem = elem + letra;
                        letra = (char) indice2.readByte();
                    }

                    cont++;
                    if (elem.compareTo(buscar) == 0) {
                        band = true;

                        archivoDatos.seek(dire);

                        String longitud = "";
                        char letra2 = (char) archivoDatos.readByte();

                        while (letra2 != '|') {

                            longitud = longitud + letra2;
                            letra2 = (char) archivoDatos.readByte();
                        }

                        int largo = Integer.parseInt(longitud);

                        reg = "";
                        for (int j = 0; j < largo; j++) {
                            reg = reg + (char) archivoDatos.readByte();
                        }

                        dtm.addRow(new Object[]{reg});
                        elem = "";
                    }
                    puntero = indice2.getFilePointer();
                }
                if (band == false) {
                    JOptionPane.showMessageDialog(this, "No se encontro la clave");
                }
                //------------------------------------------------------------------
            } else if (i == 2) {
                indice3.seek(0);
                while (elem.compareTo(buscar) < 0 && puntero != indice3.length()) {

                    dire = indice3.readLong();

                    elem = "";
                    cadRegistro = "";
                    char letra = (char) indice3.readByte();
                    while (letra != '|') {
                        elem = elem + letra;
                        letra = (char) indice3.readByte();
                    }

                    cont++;
                    if (elem.compareTo(buscar) == 0) {
                        band = true;

                        archivoDatos.seek(dire);

                        String longitud = "";
                        char letra2 = (char) archivoDatos.readByte();

                        while (letra2 != '|') {

                            longitud = longitud + letra2;
                            letra2 = (char) archivoDatos.readByte();
                        }

                        int largo = Integer.parseInt(longitud);

                        reg = "";
                        for (int j = 0; j < largo; j++) {
                            reg = reg + (char) archivoDatos.readByte();
                        }

                        dtm.addRow(new Object[]{reg});
                        elem = "";
                    }
                    puntero = indice3.getFilePointer();
                }
                if (band == false) {
                    JOptionPane.showMessageDialog(this, "No se encontro la materia");
                }
                //----------------------------------------------------------------
            } else if (i == 3) {
                indice4.seek(0);
                while (elem.compareTo(buscar) < 0 && puntero != indice4.length()) {

                    dire = indice4.readLong();

                    elem = "";
                    cadRegistro = "";
                    char letra = (char) indice4.readByte();
                    while (letra != '|') {
                        elem = elem + letra;
                        letra = (char) indice4.readByte();
                    }

                    cont++;
                    if (elem.compareTo(buscar) == 0) {
                        band = true;

                        archivoDatos.seek(dire);

                        String longitud = "";
                        char letra2 = (char) archivoDatos.readByte();

                        while (letra2 != '|') {

                            longitud = longitud + letra2;
                            letra2 = (char) archivoDatos.readByte();
                        }

                        int largo = Integer.parseInt(longitud);

                        reg = "";
                        for (int j = 0; j < largo; j++) {
                            reg = reg + (char) archivoDatos.readByte();
                        }

                        dtm.addRow(new Object[]{reg});
                        elem = "";
                    }
                    puntero = indice4.getFilePointer();
                }
                if (band == false) {
                    JOptionPane.showMessageDialog(this, "No se encontro el nombre");
                }
                //-------------------------------------------------------------------
            } else if (i == 4) {
                indice5.seek(0);
                while (elem.compareTo(buscar) < 0 && puntero != indice5.length()) {

                    dire = indice5.readLong();

                    elem = "";
                    cadRegistro = "";
                    char letra = (char) indice5.readByte();
                    while (letra != '|') {
                        elem = elem + letra;
                        letra = (char) indice5.readByte();
                    }

                    cont++;
                    if (elem.compareTo(buscar) == 0) {
                        band = true;

                        archivoDatos.seek(dire);

                        String longitud = "";
                        char letra2 = (char) archivoDatos.readByte();

                        while (letra2 != '|') {

                            longitud = longitud + letra2;
                            letra2 = (char) archivoDatos.readByte();
                        }

                        int largo = Integer.parseInt(longitud);

                        reg = "";
                        for (int j = 0; j < largo; j++) {
                            reg = reg + (char) archivoDatos.readByte();
                        }

                        dtm.addRow(new Object[]{reg});
                        elem = "";
                    }
                    puntero = indice5.getFilePointer();
                }
                if (band == false) {
                    JOptionPane.showMessageDialog(this, "No se encontro el apellido");
                }
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int fila = tblDatos.getSelectedRow();
        dtm.removeRow(fila);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean acces = false;
        User in = new User();
        in.setVisible(true);
        acces = true;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxOpciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextbuscar;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables

    private void JOptinPaneshowMessage(Object object, String no_existe_crn) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
